### ISSUE TITLE
Unable to fetch tokens

### ISSUE THREAD

**Issue by biesbjerg** [christianpanton/eboks-mailer#3]
Did E-boks change their login endpoint?

```
RESULT CODE: 1 

ERROR OUTPUT: 
Traceback (most recent call last): 
File "/opt/eboks-mailer/eboks-mailer.py", line 60, in <module> 
r.raise_for_status() 
File "/usr/lib/python2.7/dist-packages/requests/models.py", line 825, in raise_for_status 
raise HTTPError(http_error_msg, response=self) 
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error 

STANDARD OUTPUT: 
[*] Using backend: smtp 
[*] Fetching tokens from login page
```

**Comment by christianpanton** [comment]
I think they might have disabled it altogether...

**Comment by EmilMelgaard** [comment]
@christianpanton, I had the same issue with my own e-boks downloader and I decided to reverse engineer the smartphone app API.

You can use my documentation if you like: http://docs.eboksmobilexmlapi.apiary.io/

**Comment by talpadk** [comment]
It would be VERY nice to mention it in the README.md file if this project no longer works with the current API.
As it prevents others from trying install it and attempt to debug why the script returns:
```
Traceback (most recent call last):
  File "./eboks-mailer.py", line 63, in <module>
    viewstate = soup.select("#__VIEWSTATE")[0]['value']
IndexError: list index out of range
```
(The login URL only contains a redirect)

Links to other working implementations would also be appreciated as I personally hate e-boks

**Comment by christianpanton** [comment]
Sorry about that, I have been neglecting this project for a while. I have updated the README. I am looking into implementing the mobile-app API.
